config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :readers do
    collection do
      post :search_my_books
    end
  end
  devise_for :users
  root "books#index"
  resources :books do
    resources :book_orders, only:[:new, :show, :create]
  end
  resources :genres
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :genre
  has_one_attached :picture
  has_many :book_orders
  validates :title, presence: true, length: { minimum: 3, maximum: 250 }
  validates :author, presence: true, length: { minimum: 3, maximum: 250 }
end

app/models/book_order.rb
class BookOrder < ApplicationRecord
  belongs_to :reader
  belongs_to :book
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :books, :dependent => :destroy

  validates :name, presence: true, length: { maximum: 250 }
end

app/models/reader.rb
class Reader < ApplicationRecord
  before_save :generate_read_ticket
  has_many :book_orders

  validates :passport_number, uniqueness: true

  def generate_read_ticket
    self.read_ticket = Digest::SHA1.hexdigest self.passport_number
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :address, :passprot_id])
  end
end

app/controllers/book_orders_controller.rb
class BookOrdersController < ApplicationController

  before_action :set_book_order, only: [:show, :edit, :update, :destroy]
  before_action :set_book, only: [:new, :create]

  def new
    @book_order = BookOrder.new
  end

  def create
    @reader = Reader.find_by(read_ticket: params[:book_order][:reader])
    @book_order = BookOrder.new(book_order_params)
    @book_order.reader = @reader
    @book_order.book = @book
      if @book_order.save
        @book.update_attribute(:availability, false)
        redirect_to root_path, notice: 'Book order was successfully created.'
      else
        render :new
      end
    end
  end

  private

  def set_book_order
    @book_order = BookOrder.find(params[:id])
  end

  def set_book
    @book = Book.find(params[:book_id])
  end

  def book_order_params
    params.require(:book_order).permit(:return_date)
  end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books  = Book.all()
  end

  def new
    @book = Book.new()
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def upload_picture
    @book.picture.attach(uploaded_file) if uploaded_file.present?
  end

  def uploaded_file
    params[:book][:picture]
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end


  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :genre_id, :picture, :availability)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def new
    @genre = Genre.new
  end

  def show
    @genre = Genre.find(params[:id])
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    if  @genre.save
      redirect_to genres_path
    else
      render 'new'
    end
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to genre_path
    else
      render 'edit'
    end
  end


  def destroy
    Genre.destroy(params[:id])
    redirect_to genre_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
  before_action :set_reader, only: [:show, :edit, :update, :destroy]

  def index
    @reader = Reader.all()
  end

  def new
    @reader = Reader.new()
  end

  def create
    @reader = Reader.new(reader_params)

    respond_to do |format|
      if @reader.save
        format.html { redirect_to @reader, notice: 'Reader was successfully created.' }
        format.json { render :show, status: :created, location: @reader }
      else
        format.html { render :new }
        format.json { render json: @reader.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def search_my_books
    if params[:user][:read_ticket].present?
      @reader = Reader.find_by(read_ticket: params[:user][:read_ticket])
      @book_orders = @reader.book_orders
      if @reader.present?
        render 'index'
      else
        flash[:notice] = "Enter the correct data"
        render 'index'
      end
    else
      redirect_back(fallback_location: root_path)
    end
  end


  private

  def set_reader
    @reader = Reader.find(params[:id])
  end


  def reader_params
    params.require(:reader).permit(:full_name, :address, :passport_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_orders_helper.rb
module BookOrdersHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/readers_helper.rb
module ReadersHelper
end

app/views/book_orders/_form.html.erb
<%= simple_form_for [@book, @book_order] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :reader %>
    <%= f.input :return_date, as: :datetime %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Apply" %>
  </div>
<% end %>

app/views/book_orders/new.html.erb
<h1>New Book Order</h1>

<%= render 'form', book_order: @book_order %>

<%#= link_to 'Back', book_orders_path %>

app/views/book_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reader:</strong>
  <%= @book_order.reader %>
</p>

<p>
  <strong>Book:</strong>
  <%= @book_order.book %>
</p>

<p>
  <strong>Return date:</strong>
  <%= @book_order.return_date %>
</p>

<%= link_to 'Edit', edit_book_order_path(@book_order) %> |
<%= link_to 'Back', book_orders_path %>

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.input :title, label: 'Title' %>
  <%= f.input :author, label: 'Author' %> <br />
  <p>
    <%= f.label :genre %>
    <%= f.collection_select :genre_id, Genre.all, :id, :name %>
  </p> <br />
  <%= f.file_field :picture %><br />
<% end %>

app/views/books/index.html.erb
<table class="table table-striped">

  <tr>
    <th>Title:</th>
    <th>Picture: </th>
    <th>Genre:</th>
    <th>Actions:</th>
  </tr>

  <% @books.each do |book| %>
    <tr>
      <td> <%= book.title %></td>
      <td>

        <% if book.picture.attached? %>
          <%= image_tag book.picture, size: 100 %>
        <% end %>
      </td>
      <td><%= book.genre.name %></td>
      <% if book.availability? %>
      <td>
        <%= link_to 'Get book', new_book_book_order_path(book, BookOrder.new) %>
      </td>
      <% else %>
        <td>
          <% if book.book_orders.last.present? %>
          <p>Waiting for <%= book.book_orders.last.return_date.to_time %></p>
            <% end %>
        </td>
        <% end %>
    </tr>

  <% end %>

</table>

app/views/books/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= render 'form' %>
      <br>
      <%= link_to "Back", root_path(@book), :class => "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/genres/_form.html.erb
<%= simple_form_for @genre do |f| %>
  <%= f.input :name, label: 'Title' %>
  <%= f.submit 'Create', :class => "btn btn-primary" %>
<% end %>

app/views/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= render 'form' %>
      <br>
      <%= link_to "Edit genre", genre_path(@genre), :class => "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/genres/index.html.erb
<div class="container">
  <h1>Genres</h1>


  <table class="table table-striped">
    <tr>
      <th>Name</th>
    </tr>

    <% @genres.each do |genre| %>
      <tr>
        <td><%= link_to "#{genre.name}", genre_path(genre) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/genres/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= render 'form' %>
      <br>
      <%= link_to "Back", genres_path , :class => "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/genres/show.html.erb
<div class="container">
  <div class="row">
      <div class="col-8">
        <p id="notice"><%= notice %></p>
        <h1>All books of this genre</h1>


        <table class="table table-striped">

          <tr>
            <th>Title:</th>
            <th>Picture: </th>
            <th>Genre:</th>
            <th>Actions:</th>
          </tr>

          <% @genre.books.each do |book| %>
            <tr>
              <td> <%= book.title %></td>
              <td>

                <% if book.picture.attached? %>
                  <%= image_tag book.picture, size: 100 %>
                <% end %>
              </td>
              <td><%= book.genre.name %></td>
              <% if book.availability? %>
                <td>
                  <%= link_to 'Get book', new_book_book_order_path(book, BookOrder.new) %>
                </td>
              <% else %>
                <td>
                  <p>Waiting for <%= book.book_orders.last.return_date.to_time %></p>
                </td>
              <% end %>
            </tr>

          <% end %>

        </table>


      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      &#x2630;
    </button>


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <%= link_to 'Home page', root_path, class: 'navbar-brand' %>
        <%= link_to 'Genres', genres_path, class: 'navbar-brand' %>

        <%= link_to 'Search my Books', readers_path, class: 'nav-link' %>
      </ul>
      <div class="navbar-nav ml-auto">
        <div>
          <%= link_to 'Sign in for Admin', new_user_session_path, class: 'nav-link' %>
        </div>

        <div>
          <%= link_to 'Get reader ticket', new_reader_path, class: 'nav-link' %>
        </div>

          </div>


          <div class="dropdown show">
            <% if current_user.present? %>
              <%= link_to current_user.email, edit_user_registration_path(current_user), class: 'btn btn-secondary dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>
            <% end %>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'dropdown-item' %>
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            </div>
            <div>
        </div>
        </div>
        </div>
  </div>

</nav>

<% flash.each do |message_type, message| %>
    <div class="callout callout-<%= message_type %>" id="flash_message">
      <p><%= message %></p>
  </div>
<% end %>

<%= yield %>
</body>
</html>

app/views/readers/_form.html.erb
<%= simple_form_for(@reader) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :full_name %>
    <%= f.input :address %>
    <%= f.input :passport_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Get read ticket" %>
  </div>
<% end %>

app/views/readers/create.html.erb
<h1>Readers#create</h1>
<p>Find me in app/views/readers/create.html.erb</p>

app/views/readers/index.html.erb
<%= simple_form_for :user, :url => search_my_books_readers_path, :method => :post do |f| %>
  <%= f.input :read_ticket, label: 'Read ticket' %>
  <%= f.submit 'Search',  :class => "btn btn-primary" %>
<% end %>

<% if @book_orders.present? && !@book_orders.empty? %>
  <% @book_orders.each do |book_order| %>
    <p><%= book_order.book.title %></p>
    <% if book_order.book.availability? %>
      <p>Status = returned</p>
    <% elsif Time.now < book_order.return_date %>
      <p>Status = Waiting</p>
    <% elsif Time.now > book_order.return_date %>
      <p>Status = Expired</p>
    <% end  %>
  <% end %>
<% end %>

app/views/readers/new.html.erb
<h1>New Reader</h1>

<%= render 'form', reader: @reader %>

<%= link_to 'Back', readers_path %>

app/views/readers/search_my_books.html.erb
<%= simple_form_for :reader, :url => search_my_books_readers_path, :method => :get do |f| %>
  <%= f.input :read_ticket, label: 'Read ticket' %>
  <%= f.submit 'Create', :class => "btn btn-primary" %>
<% end %>

app/views/readers/show.html.erb
<p>
  <strong>Your read ticket:</strong>
  <%= @reader.read_ticket %>
</p>

<%= link_to 'Back', readers_path %>